name: compartment_proteostasis
channels:
  - conda-forge
  - defaults
dependencies:
  - seaborn
  - altair
  - numba[version='>=0.43.1']
  - scipy
  - pip
  - numpy
  - matplotlib
  - jupyter
  - mkl=2019.3
  - python[version='<=3.7']
  - ipykernel
  - pyqt
  - scikit-image
  - napari
  - xlsxwriter
  - pip:
    - cellpose==0.0.2.8
    - loguru