name: compartment_proteostasis

channels:
- defaults
- conda-forge

dependencies:
- napari==0.4.6
- numpy==1.20.1
- pandas==1.2.3
- matplotlib==3.3.4
- seaborn==0.11.1
- scikit-image==0.18.1
- jupyter==1.0.0
- ipykernel==5.5.0
- pip:
  - cellpose==0.6.1
  - loguru==0.5.3
